default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  primary: &primary_production
    <<: *default
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: ex3_rsmp      # 各自のDB名に変更
    username: ex3_rsmp_user  # 各自のユーザ名に変更
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>

