production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ex3_rsmp          # Render の DB 名
  username: ex3_rsmp_user     # Render のユーザー名
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
  host: dpg-d3ih34re5dus7394ugrg-a   # Render のホスト名
  port: 5432

 
  cache:
    adapter: postgresql
    encoding: unicode
    database: ex3_rsmp
    username: ex3_rsmp_user
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    host: dpg-d3ih34re5dus7394ugrg-a
    port: 5432

  queue:
    adapter: postgresql
    encoding: unicode
    database: ex3_rsmp
    username: ex3_rsmp_user
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    host: dpg-d3ih34re5dus7394ugrg-a
    port: 5432

